### ISSUE TITLE
Can this method be used for non-regular region?

### ISSUE THREAD

**Issue by tu1620808124** [tlroy/thermalporous#1]
Hello. Dr. Roy, I saw this simulation in your paper in a regular region with a grid, what I want to know is whether this approach especially the discrete method can be modified  to a non-regular region based on an unstructured grid. I want to do this but I don't know if it's possible.

**Comment by tlroy** [comment]
Hello. The discretization scheme is equivalent to the Finite Volume method with Two-point-flux approximation (TPFA). That method works on unstructured grids if they satisfy a certain orthogonality condition (see brief explanation on page 51 of my PhD thesis: in each cell, there exists a point called the center of the cell such that for any adjacent cell, the straight line between the two centers is orthogonal to the boundary between the cells). Does this answer your question?

**Comment by tu1620808124** [comment]
Thank you very much, I get it！
